const e=JSON.parse('{"key":"v-ccb3acce","path":"/notes/js/12.html","title":"15.错误处理机制","lang":"zh-CN","frontmatter":{},"excerpt":"","headers":[{"level":2,"title":"15.1 Error 实例对象","slug":"_15-1-error-实例对象","link":"#_15-1-error-实例对象","children":[]},{"level":2,"title":"15.2 原生错误类型","slug":"_15-2-原生错误类型","link":"#_15-2-原生错误类型","children":[{"level":3,"title":"15.2.1 SyntaxError 对象","slug":"_15-2-1-syntaxerror-对象","link":"#_15-2-1-syntaxerror-对象","children":[]},{"level":3,"title":"15.2.2 ReferenceError 对象","slug":"_15-2-2-referenceerror-对象","link":"#_15-2-2-referenceerror-对象","children":[]},{"level":3,"title":"15.2.3 RangeError 对象","slug":"_15-2-3-rangeerror-对象","link":"#_15-2-3-rangeerror-对象","children":[]},{"level":3,"title":"15.2.4 TypeError 对象","slug":"_15-2-4-typeerror-对象","link":"#_15-2-4-typeerror-对象","children":[]},{"level":3,"title":"15.2.5 URIError 对象","slug":"_15-2-5-urierror-对象","link":"#_15-2-5-urierror-对象","children":[]},{"level":3,"title":"15.2.6 EvalError 对象","slug":"_15-2-6-evalerror-对象","link":"#_15-2-6-evalerror-对象","children":[]},{"level":3,"title":"15.2.7 总结","slug":"_15-2-7-总结","link":"#_15-2-7-总结","children":[]}]},{"level":2,"title":"15.3 自定义错误","slug":"_15-3-自定义错误","link":"#_15-3-自定义错误","children":[]},{"level":2,"title":"15.4 throw 语句","slug":"_15-4-throw-语句","link":"#_15-4-throw-语句","children":[]},{"level":2,"title":"15.5 try...catch 结构","slug":"_15-5-try-catch-结构","link":"#_15-5-try-catch-结构","children":[]},{"level":2,"title":"15.6 finally 代码块","slug":"_15-6-finally-代码块","link":"#_15-6-finally-代码块","children":[]}],"git":{"updatedTime":1667873918000,"contributors":[{"name":"wanghanyu","email":"1453300745@qq.com","commits":1}]},"filePathRelative":"notes/js/12.md"}');export{e as data};
